name: Check
on:
  push:
    branches:
    - main
    - workflow_check
  pull_request:
    branches:
    - main

jobs:
  check:
    name: check
    runs-on: ubuntu-20.04
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1

    steps:
    - name: Install Mingw-w64
      shell: bash
      run: sudo apt install -y --no-install-recommends gcc-mingw-w64-i686
    - name: Checkout repository
      uses: actions/checkout@v2
    # can't use actions-rs/toolchain@v1: https://github.com/actions-rs/toolchain/issues/126
    - name: Install Rust
      shell: bash
      run: rustup show

    - name: Check build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release
    - name: Check fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
